import AsyncStorage from '@react-native-async-storage/async-storage';
import { getStreakData } from './meditationStorage';
import { allowEmptyChatSnapshotSyncForMs, scheduleSnapshotSync } from './cloudSync';
import { trackEvent, bucketTextLength } from './analytics';

// ===================
// STORAGE KEYS
// ===================

const CHAT_KEYS = {
  CONVERSATIONS: 'seedmind_conversations',
  ACTIVE_CHAT_ID: 'seedmind_active_chat_id',
};

// One-time "force open" request used when navigating from Garden -> Chat.
// This avoids auto-opening a conversation on app launch, while still enabling explicit navigation.
const FORCE_OPEN_CHAT_ID_KEY = 'seedmind_force_open_chat_id_v1';

// ===================
// TYPES
// ===================

export interface ChatMessage {
  id: string;
  text: string;
  isUser: boolean;
  timestamp: string;
}

export interface LoggedSeedBasic {
  id: string;
  action: string;
}

export type ChatPhase = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 'completed';

// Personalized seed suggestion (matches deepseekApi.ts PersonalizedSeed)
export interface StoredPersonalizedSeed {
  emoji: string;
  action: string;
  theyFeel: string;
  youReceive: string;
}

// Personalized content generated by DeepSeek for this conversation
export interface StoredPersonalizedContent {
  mirrorExplanation: string;
  reciprocalLaw: string;
  seeds: StoredPersonalizedSeed[];
}

export interface ChatConversation {
  id: string;
  title: string;
  category: string;
  // Optional custom label for the "general/Another goal" category (Garden picker + subtitle).
  // This does NOT rename the journey title/problem title; it's only the category label.
  generalCategoryLabel?: string;
  // Optional journey customization when category is `general` ("Other goal")
  journeyDisplayEmoji?: string;
  journeyMeditationId?: string;
  // Language of this conversation thread (so history stays in the original language)
  language?: 'en' | 'ru';
  messages: ChatMessage[];
  phase: ChatPhase;
  seedsLogged: LoggedSeedBasic[];
  meditationCompleted: boolean;
  createdAt: string;
  updatedAt: string;
  // Personalized content (generated by DeepSeek, persisted for consistency)
  personalizedContent?: StoredPersonalizedContent;
  // Whether this was the user's first conversation (for layout decisions)
  isFirstConversation?: boolean;
  // Experience selection data (for personalization)
  selectedExperiences?: string[];
  experienceOptions?: { emoji: string; text: string }[];
  // Heavy topic flag (for different flow: war, disability, deep trauma)
  isHeavyTopic?: boolean;
  // Post-completion mode flags (for restoring chat state)
  isInPostCompletionMode?: boolean;
  postCompletionChatMode?: boolean;
  // Conversation mode: 'problem' for challenges, 'goal' for aspirations
  conversationMode?: 'problem' | 'goal';

  // Phase 1 monetization: when true, this conversation is allowed to plant seeds (consumes a "Garden Ticket" once)
  gardenTicketed?: boolean;
}

// ===================
// HELPER FUNCTIONS
// ===================

const generateChatId = (): string => {
  return `chat_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
};

// Generic conversation starters that shouldn't be used as unique titles
const GENERIC_STARTERS = [
  "i'm struggling with money",
  "my relationships feel stuck",
  "i can't find inner peace",
  "i feel stuck in my career",
  "i'm dealing with health issues",
  "i feel lonely and isolated",
];

// Generic phrases to remove from titles
const GENERIC_PHRASES = [
  "i'm struggling with",
  "i struggle with",
  "i'm stressed about",
  "i'm worried about",
  "i'm having trouble with",
  "i need help with",
  "i'm concerned about",
  "i'm anxious about",
  "i'm afraid of",
  "i'm scared of",
  "i want to",
  "i need to",
  "i'm feeling",
  "i feel like",
  "i feel",
  "i have been",
  "i have",
  "i am",
  "i'm",
];

// Check if a message is a generic conversation starter
const isGenericStarter = (message: string): boolean => {
  const lowerMessage = message.toLowerCase().trim();
  return GENERIC_STARTERS.some(starter => 
    lowerMessage === starter || lowerMessage.startsWith(starter)
  );
};

// Clean a message by removing generic phrases
const cleanMessageForTitle = (message: string): string => {
  let cleanMessage = message.toLowerCase().trim();
  
  for (const phrase of GENERIC_PHRASES) {
    if (cleanMessage.startsWith(phrase)) {
      cleanMessage = cleanMessage.substring(phrase.length).trim();
      break;
    }
  }
  
  return cleanMessage;
};

// Find the most unique/specific message from a list of user messages
const findMostUniqueMessage = (userMessages: string[]): string => {
  // Filter out generic starters and very short messages
  const specificMessages = userMessages.filter(msg => {
    const lower = msg.toLowerCase().trim();
    // Skip generic starters
    if (isGenericStarter(msg)) return false;
    // Skip very short responses like "yes", "no", "okay"
    if (lower.length < 15) return false;
    // Skip common short responses
    if (['yes', 'no', 'okay', 'ok', 'sure', 'thanks', 'thank you'].includes(lower)) return false;
    return true;
  });
  
  if (specificMessages.length > 0) {
    // Return the first specific message (usually contains the problem details)
    return specificMessages[0];
  }
  
  // Fallback to first message if no specific ones found
  return userMessages[0] || '';
};

const generateTitle = (message: string, category: string): string => {
  const cleanMessage = cleanMessageForTitle(message);
  
  // Capitalize first letter and get first 40 chars of the unique part
  const uniquePart = cleanMessage.charAt(0).toUpperCase() + cleanMessage.slice(1);
  const preview = uniquePart.length > 40 
    ? uniquePart.substring(0, 40) + '...'
    : uniquePart;
  
  // Category emoji map
  const categoryEmojis: Record<string, string> = {
    money: '💰',
    loneliness: '💝',
    relationship: '❤️',
    career: '⭐',
    health: '🌿',
    general: '🎯',
    peace: '🧘',
  };
  
  const emoji = categoryEmojis[category] || '✨';
  return `${emoji} ${preview}`;
};

// Generate a smart title from all user messages in a conversation
const generateSmartTitle = (userMessages: string[], category: string): string => {
  const bestMessage = findMostUniqueMessage(userMessages);
  return generateTitle(bestMessage, category);
};

// ===================
// CONVERSATION MANAGEMENT
// ===================

// Get all conversations
export const getAllConversations = async (): Promise<ChatConversation[]> => {
  try {
    const data = await AsyncStorage.getItem(CHAT_KEYS.CONVERSATIONS);
    if (data) {
      const conversations: ChatConversation[] = JSON.parse(data);
      // Sort by updatedAt, most recent first
      return conversations.sort((a, b) => 
        new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime()
      );
    }
    return [];
  } catch (error) {
    console.error('Error getting conversations:', error);
    return [];
  }
};

// Get a single conversation by ID
export const getConversation = async (chatId: string): Promise<ChatConversation | null> => {
  try {
    const conversations = await getAllConversations();
    return conversations.find(c => c.id === chatId) || null;
  } catch (error) {
    console.error('Error getting conversation:', error);
    return null;
  }
};

export const markConversationGardenTicketed = async (chatId: string): Promise<void> => {
  try {
    const conversations = await getAllConversations();
    const idx = conversations.findIndex(c => c.id === chatId);
    if (idx === -1) return;
    const now = new Date().toISOString();
    const updated: ChatConversation = {
      ...conversations[idx],
      gardenTicketed: true,
      updatedAt: now,
    };
    const next = [...conversations];
    next[idx] = updated;
    await AsyncStorage.setItem(CHAT_KEYS.CONVERSATIONS, JSON.stringify(next));
    scheduleSnapshotSync();
  } catch (error) {
    console.error('Error marking conversation gardenTicketed:', error);
  }
};

// Get the active chat ID
export const getActiveChatId = async (): Promise<string | null> => {
  try {
    return await AsyncStorage.getItem(CHAT_KEYS.ACTIVE_CHAT_ID);
  } catch (error) {
    console.error('Error getting active chat ID:', error);
    return null;
  }
};

// Set the active chat ID
export const setActiveChatId = async (chatId: string | null): Promise<void> => {
  try {
    if (chatId) {
      await AsyncStorage.setItem(CHAT_KEYS.ACTIVE_CHAT_ID, chatId);
    } else {
      await AsyncStorage.removeItem(CHAT_KEYS.ACTIVE_CHAT_ID);
    }
  } catch (error) {
    console.error('Error setting active chat ID:', error);
  }
};

export const setForceOpenChatId = async (chatId: string): Promise<void> => {
  try {
    const trimmed = String(chatId || '').trim();
    if (!trimmed) return;
    await AsyncStorage.setItem(FORCE_OPEN_CHAT_ID_KEY, trimmed);
  } catch {
    // ignore
  }
};

export const consumeForceOpenChatId = async (): Promise<string | null> => {
  try {
    const raw = await AsyncStorage.getItem(FORCE_OPEN_CHAT_ID_KEY);
    if (!raw) return null;
    await AsyncStorage.removeItem(FORCE_OPEN_CHAT_ID_KEY);
    return String(raw || '').trim() || null;
  } catch {
    return null;
  }
};

// Create a new conversation
export const createConversation = async (
  firstUserMessage: string,
  category: string = 'general',
  language: 'en' | 'ru' = 'en'
): Promise<ChatConversation> => {
  try {
    const conversations = await getAllConversations();
    
    // Check if this is the user's first conversation (no completed conversations yet)
    const hasCompletedConversation = conversations.some(c => 
      c.phase === 'completed' || c.meditationCompleted
    );
    
    const newConversation: ChatConversation = {
      id: generateChatId(),
      title: generateTitle(firstUserMessage, category),
      category,
      language,
      messages: [],
      phase: 1,
      seedsLogged: [],
      meditationCompleted: false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      isFirstConversation: !hasCompletedConversation,
    };
    
    conversations.unshift(newConversation);
    await AsyncStorage.setItem(CHAT_KEYS.CONVERSATIONS, JSON.stringify(conversations));
    await setActiveChatId(newConversation.id);
    scheduleSnapshotSync('chat:createConversation');
    trackEvent('journey_created', {
      journey_id: newConversation.id,
      category,
      language,
      first_message_len: bucketTextLength(firstUserMessage),
    }).catch(() => {});
    
    return newConversation;
  } catch (error) {
    console.error('Error creating conversation:', error);
    throw error;
  }
};

// Update a conversation
export const updateConversation = async (
  chatId: string,
  updates: Partial<Omit<ChatConversation, 'id' | 'createdAt'>>
): Promise<ChatConversation | null> => {
  try {
    const conversations = await getAllConversations();
    const index = conversations.findIndex(c => c.id === chatId);
    
    if (index === -1) return null;
    
    conversations[index] = {
      ...conversations[index],
      ...updates,
      updatedAt: new Date().toISOString(),
    };
    
    await AsyncStorage.setItem(CHAT_KEYS.CONVERSATIONS, JSON.stringify(conversations));
    scheduleSnapshotSync('chat:updateConversation');
    return conversations[index];
  } catch (error) {
    console.error('Error updating conversation:', error);
    return null;
  }
};

// Add messages to a conversation
export const addMessagesToConversation = async (
  chatId: string,
  newMessages: ChatMessage[]
): Promise<boolean> => {
  try {
    const conversations = await getAllConversations();
    const index = conversations.findIndex(c => c.id === chatId);
    
    if (index === -1) return false;
    
    conversations[index].messages = [
      ...conversations[index].messages,
      ...newMessages,
    ];
    conversations[index].updatedAt = new Date().toISOString();
    
    await AsyncStorage.setItem(CHAT_KEYS.CONVERSATIONS, JSON.stringify(conversations));
    scheduleSnapshotSync('chat:addMessages');
    return true;
  } catch (error) {
    console.error('Error adding messages:', error);
    return false;
  }
};

// Update conversation phase
export const updateConversationPhase = async (
  chatId: string,
  phase: ChatPhase
): Promise<boolean> => {
  try {
    const result = await updateConversation(chatId, { phase });
    return result !== null;
  } catch (error) {
    console.error('Error updating phase:', error);
    return false;
  }
};

// Update conversation category and title (uses smart title from all user messages)
export const updateConversationCategory = async (
  chatId: string,
  category: string,
  _firstMessage: string // Kept for backward compatibility, but we now look at all messages
): Promise<boolean> => {
  try {
    // Get the conversation to access all messages
    const conversation = await getConversation(chatId);
    if (!conversation) return false;
    
    // Get all user messages
    const userMessages = conversation.messages
      .filter(m => m.isUser)
      .map(m => m.text);
    
    // Generate smart title from the most unique message
    const smartTitle = userMessages.length > 0 
      ? generateSmartTitle(userMessages, category)
      : generateTitle(_firstMessage, category);
    
    const result = await updateConversation(chatId, { 
      category,
      title: smartTitle,
    });
    return result !== null;
  } catch (error) {
    console.error('Error updating category:', error);
    return false;
  }
};

// Refresh conversation title based on current messages (call when more context is available)
export const refreshConversationTitle = async (chatId: string): Promise<boolean> => {
  try {
    const conversation = await getConversation(chatId);
    if (!conversation) return false;
    
    // Get all user messages
    const userMessages = conversation.messages
      .filter(m => m.isUser)
      .map(m => m.text);
    
    if (userMessages.length === 0) return false;
    
    // Generate smart title from the most unique message
    const smartTitle = generateSmartTitle(userMessages, conversation.category);
    
    // Only update if the title would actually change
    if (smartTitle !== conversation.title) {
      const result = await updateConversation(chatId, { title: smartTitle });
      return result !== null;
    }
    
    return true;
  } catch (error) {
    console.error('Error refreshing conversation title:', error);
    return false;
  }
};

// Log seeds to conversation
export const logSeedsToConversation = async (
  chatId: string,
  seeds: LoggedSeedBasic[]
): Promise<boolean> => {
  try {
    const conversation = await getConversation(chatId);
    if (!conversation) return false;
    
    const result = await updateConversation(chatId, { 
      seedsLogged: [...conversation.seedsLogged, ...seeds],
    });
    return result !== null;
  } catch (error) {
    console.error('Error logging seeds:', error);
    return false;
  }
};

// Mark meditation as completed
export const markMeditationCompleted = async (chatId: string): Promise<boolean> => {
  try {
    const result = await updateConversation(chatId, { 
      meditationCompleted: true,
      phase: 'completed',
    });
    return result !== null;
  } catch (error) {
    console.error('Error marking meditation completed:', error);
    return false;
  }
};

// Delete a conversation
export const deleteConversation = async (chatId: string): Promise<boolean> => {
  try {
    const conversations = await getAllConversations();
    const filtered = conversations.filter(c => c.id !== chatId);

    // If this results in an empty snapshot, explicitly allow syncing it so the cloud
    // gets cleared too (otherwise restore can bring it back).
    if (filtered.length === 0) {
      await allowEmptyChatSnapshotSyncForMs().catch(() => {});
    }

    await AsyncStorage.setItem(CHAT_KEYS.CONVERSATIONS, JSON.stringify(filtered));
    scheduleSnapshotSync('chat:deleteConversation');
    trackEvent('journey_deleted', { journey_id: chatId }).catch(() => {});
    
    // If deleting active chat, clear active ID
    const activeId = await getActiveChatId();
    if (activeId === chatId) {
      await setActiveChatId(null);
    }
    
    return true;
  } catch (error) {
    console.error('Error deleting conversation:', error);
    return false;
  }
};

// Check if user is experienced (has completed at least 1 meditation from any source)
export const isExperiencedUser = async (): Promise<boolean> => {
  try {
    // Check streak first - this catches meditations done from Meditations tab directly
    const streakData = await getStreakData();
    if (streakData.currentStreak > 0 || streakData.longestStreak > 0) {
      return true;
    }
    
    // Fallback: check conversations (for meditations done through chat flow)
    const conversations = await getAllConversations();
    return conversations.some(c => c.phase === 'completed' || c.meditationCompleted);
  } catch (error) {
    console.error('Error checking experienced user:', error);
    return false;
  }
};

// Get or create active conversation
export const getOrCreateActiveConversation = async (): Promise<ChatConversation | null> => {
  try {
    const activeId = await getActiveChatId();
    
    if (activeId) {
      const conversation = await getConversation(activeId);
      if (conversation) {
        return conversation;
      }
    }
    
    // No active conversation - return null (user will start fresh)
    return null;
  } catch (error) {
    console.error('Error getting active conversation:', error);
    return null;
  }
};

// Start a new chat (clears active, doesn't delete old ones)
export const startNewChat = async (): Promise<void> => {
  try {
    await setActiveChatId(null);
  } catch (error) {
    console.error('Error starting new chat:', error);
  }
};

// ===================
// UTILITY FUNCTIONS
// ===================

// Get conversation count
export const getConversationCount = async (): Promise<number> => {
  const conversations = await getAllConversations();
  return conversations.length;
};

// Clear all chat data (for testing/reset)
export const clearAllChatData = async (): Promise<void> => {
  try {
    // Keep keys consistent: store an explicit empty snapshot so cloud sync can clear too.
    await AsyncStorage.setItem(CHAT_KEYS.CONVERSATIONS, JSON.stringify([]));
    await AsyncStorage.removeItem(CHAT_KEYS.ACTIVE_CHAT_ID);
    scheduleSnapshotSync('chat:clearAllChatData');
  } catch (error) {
    console.error('Error clearing chat data:', error);
  }
};

// Get recent conversations (for history preview)
export const getRecentConversations = async (limit: number = 10): Promise<ChatConversation[]> => {
  const conversations = await getAllConversations();
  return conversations.slice(0, limit);
};

// Format conversation for display
export const formatConversationDate = (dateString: string): string => {
  const date = new Date(dateString);
  const now = new Date();
  const diffDays = Math.floor((now.getTime() - date.getTime()) / (1000 * 60 * 60 * 24));
  
  if (diffDays === 0) {
    return 'Today';
  } else if (diffDays === 1) {
    return 'Yesterday';
  } else if (diffDays < 7) {
    return `${diffDays} days ago`;
  } else {
    return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
  }
};

// Get phase display text
export const getPhaseDisplayText = (phase: ChatPhase): string => {
  if (phase === 'completed') return 'Completed ✓';
  
  const phaseTexts: Record<number, string> = {
    1: 'Sharing feelings',
    2: 'Exploring the mirror',
    3: 'Understanding seeds',
    4: 'Getting ideas',
    5: 'Ready to plant',
    6: 'Logging seeds',
    7: 'Meditating',
  };
  
  return phaseTexts[phase as number] || 'In progress';
};


